#!/bin/sh

echo Unpacking asterix distribution...
rm -rf build
mkdir build
cd build
unzip -q ../asterix*server*.zip
cd ..
cp -a asterix-startup.sh asterix-properties.xml build
chmod -R og-w build

docker build -t ceejatec/asterix-base .

(cd ../cc; ./go)
(cd ../nc; ./go)
